//
//  NLS_FourSquareApiKeys.h
//  YumFinder
//
//  Created by Summer Green on 9/22/14.
//  Copyright (c) 2014 Nimar Labs. All rights reserved.
//
#define fsMETA              @"meta"
#define fsCODE              @"code"
#define fsRESPONSE          @"response"
#define fsVENUES            @"venues"
#define fsID                @"id"
#define fsNAME              @"name"
#define fsLOCATION  		@"location"
#define fsADDRESS           @"address"
#define fsLAT               @"lat"
#define fsLNG               @"lng"
#define fsDISTANCE  		@"distance"
#define fsCC                @"cc"
#define fsCITY              @"city"
#define fsSTATE             @"state"
#define fsCOUNTRY           @"country"
#define fsFORMATTEDADDRESS  @"formattedAddress"
#define fsCATEGORIES  		@"categories"
#define fsPLURALNAME  		@"pluralName"
#define fsSHORTNAME  		@"shortName"
#define fsICON              @"icon"
#define fsPREFIX            @"prefix"
#define fsSUFFIX            @"suffix"
#define fsPRIMARY           @"primary"
#define fsVERIFIED  		@"verified"
#define fsSTATS             @"stats"
#define fsCHECKINSCOUNT  	@"checkinsCount"
#define fsUSERSCOUNT  		@"usersCount"
#define fsTIPCOUNT  		@"tipCount"
#define fsSPECIALS  		@"specials"
#define fsCOUNT             @"count"
#define fsITEMS             @"items"
#define fsHERENOW           @"hereNow"
#define fsSUMMARY           @"summary"
#define fsGROUPS            @"groups"
#define fsREFERRALID        @"referralId"
#define fsCROSSSTREET  		@"crossStreet"
#define fsPOSTALCODE  		@"postalCode"
#define fsHASMENU           @"hasMenu"
#define fsVENUEPAGE  		@"venuePage"
#define fsTYPE              @"type"
#define fsSTOREID           @"storeId"